// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dwqpkdatzdqhplgyhigg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR3cXBrZGF0emRxaHBsZ3loaWdnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzNDU5MzIsImV4cCI6MjA2NzkyMTkzMn0.yxyN30pp3ZuX8gxcib6DMdpf_8SIiGI_ag5Pcjo8lbA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});